[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[plugins]]
  package = "netlify-plugin-html-validate@1.1.1"
  [plugins.inputs]
    config = ".htmlvalidate.json"
    path = "index.html"
    ext = "html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
